name: shared
description: A package that manages shared data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  app_ui:
    path: ../app_ui
  bloc_concurrency: ^0.3.0
  blurhash: ^1.2.0
  dio: ^5.9.0
  env:
    path: ../env
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  freezed_annotation: ^3.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  image_picker_plus:
    path: ../image_picker_plus
  image_size_getter: ^2.1.2
  insta_blocks:
    path: ../insta_blocks
  intl: ^0.20.2
  jiffy: ^6.3.1
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  meta: any
  mime: ^1.0.4
  ogp_data_extract: ^0.2.2
  powersync: ^1.16.1
  stream_transform: ^2.1.0
  user_repository:
    path: ../user_repository
  uuid: ^4.4.0
  video_compress: ^3.1.4

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
