name: supabase_authentication_client
description: A Supabase implementation of the authentication client interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  authentication_client:
    path: ../authentication_client
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  powersync_repository:
    path: ../../powersync_repository
  shared:
    path: ../../shared
  supabase_flutter: ^2.10.3
  token_storage:
    path: ../token_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
