name: insta_blocks
description: Reusable Instagram Blocks for Flutter Instagram offline-first clone
  Application.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  meta: any
  shared:
    path: ../shared
  user_repository:
    path: ../user_repository

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
