name: flutter_instagram_offline_first_clone
description: A complete offline-first Flutter Instagram clone with Supabase and PowerSync.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  animations: ^2.1.0
  app_ui:
    path: packages/app_ui
  async: ^2.11.0
  bloc: ^9.1.0
  cached_memory_image: ^1.5.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  chats_repository:
    path: packages/chats_repository
  collection: ^1.18.0
  database_client:
    path: packages/database_client
  env:
    path: packages/env
  equatable: ^2.0.7
  fast_immutable_collections: ^10.2.4
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  firebase_remote_config_repository:
    path: packages/firebase_remote_config_repository
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.5
  flutter_portal: ^1.1.4
  flutter_staggered_grid_view: ^0.7.0
  form_fields:
    path: packages/form_fields
  go_router: ^14.2.7
  google_sign_in: ^6.3.0
  hydrated_bloc: ^10.1.1
  insta_blocks:
    path: packages/insta_blocks
  instagram_blocks_ui:
    path: packages/instagram_blocks_ui
  intl: ^0.20.2
  inview_notifier_list:
    git: https://github.com/Gambley1/inview_notifier_list
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  notifications_repository:
    path: packages/notifications_repository
  ogp_data_extract: ^0.2.2
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.5
  persistent_storage:
    path: packages/storage/persistent_storage
  posthog_flutter: ^4.5.0
  posts_repository:
    path: packages/posts_repository
  powersync_repository:
    path: packages/powersync_repository
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  search_repository:
    path: packages/search_repository
  shared:
    path: packages/shared
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  sprung: ^3.0.1
  stories_editor:
    path: packages/stories_editor
  stories_repository:
    path: packages/stories_repository
  story_view: ^0.16.5
  styled_text:
    git:
      ref: 91272c4779123570a642b19f96214adef2e850b4
      url: https://github.com/Maatteogekko/styled_text_package
      path: styled_text
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  timeago: ^3.7.1
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.3.2
  user_repository:
    path: packages/user_repository
  vector_math: ^2.1.4
  visibility_detector: ^0.4.0+2

dependency_overrides:
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  build_verify: ^3.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
