name: secure_storage
description: A Key/Value Secure Storage Client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
