name: storage
description: A Dart Storage Client Interface
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: ^9.0.0
