name: firebase_notifications_client
description: A Firebase Cloud Messaging notifications client.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  notifications_client:
    path: ../notifications_client
  shared:
    path: ../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
