name: env
description: A package that manages application secrets.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  envied: ^1.1.1
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.6.0
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
