name: firebase_remote_config_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  firebase_remote_config: ^6.1.0
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
