name: powersync_repository
description: A package that manages connection to the PowerSync cloud service and database.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  env:
    path: ../env

  flutter:
    sdk: flutter
  path: any
  path_provider: ^2.1.5
  powersync: ^1.16.1
  shared:
    path: ../shared
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
