name: persistent_storage
description: Storage that saves data in the device's persistent memory.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
